/*!
 * SAP UI development toolkit for HTML5 (SAPUI5)
 * (c) Copyright 2009-2013 SAP AG or an SAP affiliate company. 
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
jQuery.sap.declare("sap.ui.demokit.IndexPage");
sap.ui.demokit.IndexPage=function IndexPage(c){var h=3,C;function a(s,n){return s.split('/').slice(-n-1).join('/')}function r(){var p=top.getPagesForCategory(c);if(p!==false){for(var i=0;i<p.length;i++){that.add(true,p[i].text,'',that.sPathToRoot+p[i].ico,undefined,p[i].ref)}}else{jQuery.sap.log.debug("top page can't provide category "+c+" yet, waiting another 200ms");setTimeout(r,200)}}this.sPathToRoot=a("../../../../../../../",h);this.sRootUrl=window.location.pathname.split('/').slice(-h-1,-1).join('/')+'/';this.sColor="Blue";this.oHexGroup=new sap.ui.demokit.HexagonButtonGroup({colspan:(C||5)});if(c&&top.getPagesForCategory){var p=top.getPagesForCategory(c);for(var i=0;i<p.length;i++){this.add(true,p[i].text,'',this.sPathToRoot+p[i].ico,undefined,p[i].ref)}}};
sap.ui.demokit.IndexPage.prototype.add=function add(e,c,t,i,l,r){var a=this;if(typeof e!=="boolean"){r=l;l=i;i=t;t=c;c=e;e=true}r=r||this.sRootUrl+c+'.html';if(!l){l="sap.ui.commons"}if(!t){if(e){t="A short tutorial that explains how to use the "+c+". Click to start it."}else{t="Here you should find a tutorial for the "+c+". Unfortunately we didn't write it in time. Please hover back soon ;-)"}}var b=new sap.ui.demokit.HexagonButton({enabled:e,color:"Yellow",tooltip:new sap.ui.commons.RichTooltip({title:c,imageSrc:i?i:(e?"":this.sPathToRoot+"theme/img/Under-construction.png"),text:t}),press:function(){top.navigateTo(r)}});if(i){b.setIcon(i)}this.oHexGroup.addButton(b);return this};
sap.ui.demokit.IndexPage.prototype.placeAt=function(i){this.oHexGroup.placeAt(i);jQuery(function(){if(jQuery("#vistaico-license").size()==0){jQuery("body").append('<div id="vistaico-license" class="license">Some icon(s) created by <a class="sapUiDemokitLink" href="http://VistaICO.com" target="_blank">VistaICO.com</a> and <a class="sapUiDemokitLink" href="http://www.iconarchive.com/artist/fatcow.html" target="_blank">Fatcow Web Hosting</a>,	used under Creative Commons 3.0 Attribution Unported license</div>')}})};
